### ISSUE TITLE
Authorization button is not reacting

### ISSUE THREAD

**Issue by MeteorBoom** [SergeyShkuratko/SchoolMark#25]
На форме авторизации при нажатии на кнопку входа ничего не происходит. В логах страницы следующее сообщение:
![image](https://user-images.githubusercontent.com/16517593/31861515-2fc687a0-b737-11e7-95ff-c1d91775567c.png)

![image](https://user-images.githubusercontent.com/16517593/31861507-142e2dc2-b737-11e7-95b8-ea4e0654e984.png)

**Comment by Crazy1305** [comment]
fixed
